version: 2
jobs:
  build:
    macos:  # indicate that we are using the macOS executor
      xcode: 11.3.0 # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout
      - run: bundle install
      - run: docker build -t my-bot .
      - run: docker run my-bot