version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install
      - run: ruby bot.rb